language: node_js

script: "/bin/date"

node_js:
  - 0.10

install : npm install
script  : npm start

deploy:
  provider: s3
  access_key_id:
    secure: RSbJV8MZaIxbpJA0yT/qp+7nBPzQmjkzPErb8t4ZpAkebsTVKAd7/e//fXFJguSUoPx57zGRxCJNTvuF7uZSZ4Vl85JZXInzQnKI5nFP8FfqqSZmH6mYf6+m0MFHVYy4s0SX5/IGkMCRIFoKK3PJ7HnizrYdmTOywcSxrsSI8F0=
  secret_access_key:
    secure: bxuBwOeamiW+xysEbyJ1r1KhcHg5WtJUqDv8tIpw1t06D6AeJ0frny64bPWYq9DiOYJetqifUq9ppRdafVP4JbR5rbn9ryXkvR+NeySZ0tQZask9udwsxK8bz/YC00511TTYt7l3x24neIWqQJ3HNMJSU4bXMusdlK/wGYymn/o=
  bucket: wrio
  upload-dir: Core-WRIO-App
  acl: public_read
